///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CategoriesModelData {
/*
{
  "id": 1,
  "categoryName": "Bilgisayar Aksesuarları",
  "image": "bilgisayaraksesuarlari.png"
} 
*/

  int? id;
  String? categoryName;
  String? image;

  CategoriesModelData({
    this.id,
    this.categoryName,
    this.image,
  });
  CategoriesModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    categoryName = json['categoryName']?.toString();
    image = json['image']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['categoryName'] = categoryName;
    data['image'] = image;
    return data;
  }
}

class CategoriesModel {
/*
{
  "message": "Kategoriler başarıyla getirildi",
  "status": true,
  "data": [
    {
      "id": 1,
      "categoryName": "Bilgisayar Aksesuarları",
      "image": "bilgisayaraksesuarlari.png"
    }
  ]
} 
*/

  String? message;
  bool? status;
  List<CategoriesModelData?>? data;

  CategoriesModel({
    this.message,
    this.status,
    this.data,
  });
  CategoriesModel.fromJson(Map<String, dynamic> json) {
    message = json['message']?.toString();
    status = json['status'];
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <CategoriesModelData>[];
  v.forEach((v) {
  arr0.add(CategoriesModelData.fromJson(v));
  });
    this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['message'] = message;
    data['status'] = status;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['data'] = arr0;
    }
    return data;
  }
}
